apiVersion: apps/v1
kind: Deployment
metadata:
    name: llm-api-deployment
    labels:
        app: llm-api
spec:
    replicas: 1
    selector:
        matchLabels:
            app: llm-api
    template:
        metadata:
            name: llm-api
            labels:
                app: llm-api
        spec:
            containers:
                -   name: llm-api
                    image: llm-api:latest
                    imagePullPolicy: Never
                    ports:
                        -   containerPort: 7000
                    resources:
                        requests:
                            cpu: 100m
                        limits:
                            cpu: 200m
            restartPolicy: Always
      