apiVersion: v1
kind: Service
metadata:
    name: llm-api-service
    labels:
        app: llm-api
        monitor: "true"
spec:
    selector:
        app: llm-api
    ports:
        -   protocol: TCP
            port: 7000
            targetPort: 7000
    type: LoadBalancer
  