apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx-deployment
spec:
    replicas: 2
    selector:
        matchLabels:
            app: nginx
    template:
        metadata:
            labels:
                app: nginx
        spec:
            containers:
                - name: nginx
                  image: nginx:latest
                  ports:
                      - containerPort: 7800
                  volumeMounts:
                      - name: nginx-conf
                        mountPath: /etc/nginx/nginx.conf
                        subPath: nginx.conf
            volumes:
                - name: nginx-conf
                  configMap:
                      name: nginx-conf
