apiVersion: apps/v1
kind: Deployment
metadata:
    name: qa-api-deployment
    labels:
        app: qa-api
spec:
    selector:
        matchLabels:
            app: qa-api
    template:
        metadata:
            name: qa-api
            labels:
                app: qa-api
        spec:
            containers:
                -   name: qa-api
                    image: qa-api:latest
                    imagePullPolicy: Never
                    ports:
                        -   containerPort: 7777
                    resources:
                        requests:
                            cpu: 100m
                        limits:
                            cpu: 200m
                    env:
                        -   name: PGPASS
                            valueFrom:
                                secretKeyRef:
                                    name: qa-database-cluster-app
                                    key: pgpass
                                    optional: false
            restartPolicy: Always
      