apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: qa-api-deployment-hpa
spec:
    maxReplicas: 3
    minReplicas: 1
    targetCPUUtilizationPercentage: 10
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: qa-api-deployment
