apiVersion: v1
kind: Service
metadata:
    name: qa-api-service
    labels:
        app: qa-api
        monitor: "true"
spec:
    selector:
        app: qa-api
    ports:
        -   protocol: TCP
            port: 7777
            targetPort: 7777
    type: LoadBalancer
  